[package]
name = "quickgitcommit-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "2.33.3"
colored = "2.0.0"
inquire = "0.2.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.67"
